# Site settings
baseurl = "https://objetos.github.io/projects/"
languageCode = "en-us"
title = "UN Object Oriented Programming Course"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"


[params]
    # Meta
    title = "Object Oriented Programming"
    subtitle = "National University of Colombia Course Project Gallery"
    author = "Refer to each projects"
    description = "Object Oriented Programming projects collected during the last courses conducted at National University of Colombia"
    keywords = "OOP, source, web source, projects"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "See the project"

    # Footer text
    footertext = "Made with [Hugo](https://gohugo.io/), using the [hugrid template](https://github.com/aerohub/hugrid) adapted by [Julian Salomón] (http://github.com/JulianSalomon)"

    custom_css = ['css/style.css']
